# Generated by Django 4.2.25 on 2025-10-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='text',
        ),
    ]
