# Generated by Django 4.2.25 on 2025-10-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0002_rename_body_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
