# Generated by Django 4.2.25 on 2025-10-27 13:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static\\images\\default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
