# Generated by Django 4.2.25 on 2025-10-29 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0007_comment_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/images/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
