# Generated by Django 4.2.25 on 2025-10-30 09:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='no-profile-image', max_length=255, verbose_name='image'),
        ),
    ]
